config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :products

  # resources :users do
  #   resources :purchase
  # end

  resources :categories
  get 'home/buy'

  get 'home/index'

  get 'home/show'

  root to: "home#index"
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def show
    @purchase = Purchase.new
    @product = Product.find(params[:id])
  end

  def create
    @purchase = Purchase.new(purchase_params)

     @product = Product.find(params[:product_id])
     # @purchase.user_id = current_user.id
     if @purchase.save
      # userと買うuserを一致させるから
      user = @purchase.user
      # deliverメソッドを使って、メールを送信する
        PurchaseMailer.purchase_email(user, @purchase).deliver

     else
      redirect_to purchase_path(@purchase)
     end

    end

  def index
    #binding.pry
    @purchases = Purchase.all


     # @products = @purchase.product.find(params[:id])
    # @user = @product.user.find(params[:id])
  #   @purchase = @user.purchases.find(params[:id])
  #   @purchase = Purchase.where(user_id: current_user.id)
  end








  # ________________________________________________________
  private

    def purchase_params
        params.require(:purchase).permit(:address, :postal_code, :phone, :user_id, :product_id, :user_name)
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/index.html.erb
<span><%= link_to "index", home_index_path %></span>
<%# binding.pry %>
<% @purchases.includes(:product).each do |b| %>
  <p><%= b.user.email %></p>
  <p><%= b.product.product_name%></p>

<% end %>

app/views/purchases/show.html.erb
<h2>価格</h2>
<span><%= @product.price %>円</span>
<h2>商品名</h2>
<span><%= @product.product_name %></span>
<h2>画像</h2>
<span><%= image_tag @product.photo.url(:medium) %></span>



<h1>購入する画面</h1>

<%= form_for @purchase do |f| %>

<div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>

<div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
 <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :phone %><br>
    <%= f.telephone_field :phone %>
  </div>

  <div class="field">
    <%= f.hidden_field :product_id, value: @product.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>