config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :products

  # resources :users do
  #   resources :purchase
  # end

  resources :categories
  get 'home/buy'

  get 'home/index'

  get 'home/show'

  root to: "home#index"
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: :show

  def index
   @products = Product.page(params[:page])
  end

  def show
  end

  # def buy
  #   @user = current_user
  #   # @purchase = @user.purchases.find(params[:id])
  #   @products = @user.products.find(params[:product_id])
  #   @purchase = Purchase.where(user_id: current_user.id)
  # end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/buy.html.erb
<% @products.each do |b| %>
  <tr>
   <td><%= b.product_name %></td>
   <td><strong>¥</strong>
   <%= b.product.price %>
   </td>
   <td><%= b.product.select_item%></td>
  </tr>
  <strong><%= b.current_user.email %></strong>.

<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
 <% if admin_signed_in? %> 
<%= link_to "商品入力", new_product_path %>

<p><%= link_to "購入一覧",   purchases_path %></p>
<span><%= link_to "index",products_path %></span>



<table>
<%= page_entries_info @products %>
<% current_admin.products.each do |product| %>
<tr>
<td><%= link_to product.product_name,product_path(product.id) %></td>

<td><strong>¥</strong>
<%= product.price %>
</td>
<td><%= product.select_item%></td>

<td><%= link_to "edit", edit_product_path(product.id) %></td>
<td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>


<% end %>
  
<% end %>
<% if user_signed_in? %> 
 <span><%= link_to "index",products_path %></span>
</table>

<% end %>
<%= paginate @products, outer_window: 4 %>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>