config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :products

  # resources :users do
  #   resources :purchase
  # end

  resources :categories
  get 'home/buy'

  get 'home/index'

  get 'home/show'

  root to: "home#index"
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    
end

app/models/product.rb
class Product < ApplicationRecord
  # photoをattachファイルとする。stylesで画像サイズを定義できる
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }

  # ファイルの拡張子を指定（これがないとエラーが発生する）
  validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  belongs_to :admin
  has_many :users, through: :purchases
  has_many :purchases
  validates :product_name, presence: true
  validates :price, presence: true
  validates :description, presence: true
   # 値段は数値で0以上
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  paginates_per 5  # 1ページあたり5項目表示
  
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  # モデルのメソッドになる
  belongs_to :user
  belongs_to :product
  # 入ってないとだめなやつ
  validates :product_id, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :phone, presence: true
  validates :user_name, presence: true
  validates :phone,    length: { maximum: 11 } 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :purchases
  has_many :products, through: :purchases
  before_save { self.email = email.downcase }
  end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def create
      @category = Category.create(set_category)
      
  end

  def show
     @category = Category.find(params[:id])
     # whereは検索の条件が追加できる青の(テーブルの中のカラムの紫を探すという表記)
     @products = Product.where(category_id: @category.id)
    
  end
















#   private

#   def _params
#       params.require(:).permit()
#   end
# end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: :show

  def index
   @products = Product.page(params[:page])
  end

  def show
  end

  # def buy
  #   @user = current_user
  #   # @purchase = @user.purchases.find(params[:id])
  #   @products = @user.products.find(params[:product_id])
  #   @purchase = Purchase.where(user_id: current_user.id)
  # end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @product = Product.new
    @category = Category.new
  end

  def create
    @product = Product.new(product_params)
    @product.admin_id = current_admin.id
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def index
    @products = Product.all
    @products = Product.page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
    @product_category = Category.find(@product.category_id)
    # @category = Category.find(params)
  end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to home_index_path
  end









#_________________________________________________________________________

private

  def product_params
      params.require(:product).permit(:product_name, :price, :description, :select_item, :admin_id, :category_id, :photo)
  end
  def set_categories
    @categories = Category.all.pluck(:name)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def show
    @purchase = Purchase.new
    @product = Product.find(params[:id])
  end

  def create
    @purchase = Purchase.new(purchase_params)

     @product = Product.find(params[:product_id])
     # @purchase.user_id = current_user.id
     if @purchase.save
      # userと買うuserを一致させるから
      user = @purchase.user
      # deliverメソッドを使って、メールを送信する
        PurchaseMailer.purchase_email(user, @purchase).deliver

     else
      redirect_to purchase_path(@purchase)
     end

    end

  def index
    #binding.pry
    @purchases = Purchase.all


     # @products = @purchase.product.find(params[:id])
    # @user = @product.user.find(params[:id])
  #   @purchase = @user.purchases.find(params[:id])
  #   @purchase = Purchase.where(user_id: current_user.id)
  end








  # ________________________________________________________
  private

    def purchase_params
        params.require(:purchase).permit(:address, :postal_code, :phone, :user_id, :product_id, :user_name)
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ec7</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <body class='<%= "#{controller.controller_name}" %>'>
  </head>

  <body>
       <header>
        <nav>
         <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
         <% if user_signed_in? %> 
         <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
         <!-- *_path はUserモデルを作成したときに、
          deviseにより自動で作成されてますので、rake routesで確認できます -->
           Logged in as <strong><%= current_user.email %></strong>.
           <%= link_to 'プロフィール変更', edit_user_registration_path %> |
           <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
         <% else %>
          <%= link_to "サインイン", new_user_registration_path %> |
          <%= link_to "ログイン", new_user_session_path %>
         <% end %>

         <!-- 管理者用 -->
         <% if admin_signed_in? %> 
        
          Logged in as <strong><%= current_admin.email %></strong>.
          <%#= link_to 'adminプロフィール変更', edit_admin_registration_path %> |
          <%= link_to "adminログアウト", destroy_admin_session_path, method: :delete %>
         <% else %>
          <%#= link_to "adminサインイン", new_admin_registration_path %> |
          <%= link_to "adminログイン", new_admin_session_path %>
         <% end %>
        </nav>
       </header>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>