config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :products

  # resources :users do
  #   resources :purchase
  # end

  resources :categories
  get 'home/buy'

  get 'home/index'

  get 'home/show'

  root to: "home#index"
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  # photoをattachファイルとする。stylesで画像サイズを定義できる
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }

  # ファイルの拡張子を指定（これがないとエラーが発生する）
  validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  belongs_to :admin
  has_many :users, through: :purchases
  has_many :purchases
  validates :product_name, presence: true
  validates :price, presence: true
  validates :description, presence: true
   # 値段は数値で0以上
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  paginates_per 5  # 1ページあたり5項目表示
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @product = Product.new
    @category = Category.new
  end

  def create
    @product = Product.new(product_params)
    @product.admin_id = current_admin.id
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def index
    @products = Product.all
    @products = Product.page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
    @product_category = Category.find(@product.category_id)
    # @category = Category.find(params)
  end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to home_index_path
  end









#_________________________________________________________________________

private

  def product_params
      params.require(:product).permit(:product_name, :price, :description, :select_item, :admin_id, :category_id, :photo)
  end
  def set_categories
    @categories = Category.all.pluck(:name)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>


  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.file_field :photo %>
  
  </div>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div> 

  <div class="actions">
   <%= f.submit %>
  </div>

<% end %>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<h1>product#index</h1>
<%= page_entries_info @products %>

<table>
<% @products.each do |product| %>
<tr>
<td><%= link_to product.product_name,product_path(product.id) %></td>

<td><strong>¥</strong>
<%= product.price %>
</td>
<td><%= product.select_item%></td>


</tr>
<% end %>
</table>

<%= paginate @products, outer_window: 4 %>

app/views/products/new.html.erb
<h1>Products#new</h1>
<%= render 'form' %>
<p>Find me in app/views/products/new.html.erb</p>

app/views/products/show.html.erb
<h2>商品名</h2>
<span><%= @product.product_name %></span>

<h2>画像</h2>
<span><%= image_tag @product.photo.url(:medium) %></span>

<h2>価格</h2>
<span><%= @product.price %>円</span>

<h2>商品内容</h2>
<span><%= @product.description %></span>

<h2>アイテム</h2>
<span><%= link_to @product_category.name, category_path(@product.category_id) %></span>


<span><%= link_to "index",products_path %></span>
<span><%= link_to "購入する",purchase_path %></span>
<span><%= link_to "カテゴリーへ",categories_path %></span>

<% if admin_signed_in? %> 
<span><%= link_to "商品入力", new_product_path %></span>
<% end %>